#############################################################################
# Makefile for building: chipcoin
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  ChipCoin.pro
# Template: app
# Command: C:\Qt\5.4.2\qtbase\bin\qmake.exe USE_UPNP=- -o Makefile ChipCoin.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt\5.4.2\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ChipCoin.pro C:/Qt/5.4.2/qtbase/mkspecs/win32-g++/qmake.conf C:/Qt/5.4.2/qtbase/mkspecs/features/spec_pre.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/qdevice.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/features/device_config.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/common/shell-win32.conf \
		C:/Qt/5.4.2/qtbase/mkspecs/qconfig.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axbase.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axbase_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_axbase.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axcontainer.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axcontainer_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_axcontainer.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axserver.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_axserver_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_axserver.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_bluetooth.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_bluetooth_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_clucene_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_clucene_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_core.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_declarative.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_declarative_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_declarative.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_designer.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_designer_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_designer.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_designercomponents_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_enginio.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_enginio_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_enginio.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_gui.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_help.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_help_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_help.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_multimedia.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_multimedia_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_multimediawidgets_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_network.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_nfc.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_nfc_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_platformsupport_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_positioning.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_positioning_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_qml.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_qml_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_qml.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_qmldevtools_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_script.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_script_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_script.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_scripttools.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_scripttools_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_sensors.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_sensors_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_serialport.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_serialport_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_sql.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_svg.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_svg_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_svg.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_uitools.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_uitools_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webchannel.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webchannel_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webkit.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webkit_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_webkit.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webkitwidgets.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_webkitwidgets_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_webkitwidgets.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_websockets.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_websockets_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_winextras.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_winextras_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_winextras.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_xml.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns.pri \
		C:/QT/5.4.2/qtbase/mkspecs/modules-inst/qt_lib_xmlpatterns_private.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_dsengine.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qdds.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qicns.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qico.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qjp2.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qminimal.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qmng.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qnativewifibearer.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qsvg.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qsvgicon.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtaudio_windows.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtga.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtiff.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qwbmp.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qwebp.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_qwindows.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_plugin_windowsprintersupport.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qml.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qml1plugindump.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qmlbundle.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qmllint.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_syncqt.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_uic.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		C:/Qt/5.4.2/qtbase/mkspecs/features/qt_functions.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/qt_config.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/win32/qt_config.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/win32-g++/qmake.conf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/spec_post.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/exclusive_builds.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/default_pre.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/win32/default_pre.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/resolve_config.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/exclusive_builds_post.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/default_post.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/win32/rtti.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/precompile_header.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/warn_on.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/qt.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/resources.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/moc.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/uic.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/win32/windows.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/testcase_targets.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/exceptions.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/yacc.prf \
		C:/Qt/5.4.2/qtbase/mkspecs/features/lex.prf \
		ChipCoin.pro \
		C:/QT/5.4.2/qtbase/lib/qtmain.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Core.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5WebKitWidgets.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5WebKit.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Gui.prl \
		C:/QT/5.4.2/qtbase/lib/qtharfbuzzng.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Network.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Sensors.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Positioning.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Multimedia.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Sql.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5Widgets.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5MultimediaWidgets.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5PrintSupport.prl \
		C:/Qt/5.4.2/qtbase/plugins/platforms/qwindows.prl \
		C:/QT/5.4.2/qtbase/lib/Qt5PlatformSupport.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qdds.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qicns.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qico.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qjp2.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qmng.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qtga.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qtiff.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qwbmp.prl \
		C:/Qt/5.4.2/qtbase/plugins/imageformats/qwebp.prl \
		C:/Qt/5.4.2/qtbase/plugins/bearer/qgenericbearer.prl \
		C:/Qt/5.4.2/qtbase/plugins/bearer/qnativewifibearer.prl
	$(QMAKE) USE_UPNP=- -o Makefile ChipCoin.pro
C:\Qt\5.4.2\qtbase\mkspecs\features\spec_pre.prf:
C:\Qt\5.4.2\qtbase\mkspecs\qdevice.pri:
C:\Qt\5.4.2\qtbase\mkspecs\features\device_config.prf:
C:\Qt\5.4.2\qtbase\mkspecs\common\shell-win32.conf:
C:\Qt\5.4.2\qtbase\mkspecs\qconfig.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axbase_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_axbase.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axcontainer_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_axcontainer.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_axserver_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_axserver.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_bluetooth_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_clucene_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_clucene_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_core_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_declarative_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_declarative.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_designer.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_designer_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_designer.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_designercomponents_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_enginio.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_enginio_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_enginio.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_help_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_help.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_multimedia_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_network_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_nfc.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_nfc_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_positioning.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_positioning_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_qml_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_qml.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_script_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_script.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_scripttools_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_sensors_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_sensors.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_serialport_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_svg.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_svg_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_uitools_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_uitools.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webchannel.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webchannel_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_webchannel.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webkit.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webkit_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_webkit.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webkitwidgets.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_webkitwidgets_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_webkitwidgets.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_websockets.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_websockets_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_winextras.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_winextras_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
C:\QT\5.4.2\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_dsengine.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qdds.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qdeclarativeview.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qicns.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qico.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qjp2.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qmng.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qsvg.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtaudio_windows.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtga.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtiff.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtposition_positionpoll.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qwebp.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_lconvert.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_lrelease.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_lupdate.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qcollectiongenerator.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qhelpgenerator.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qml.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qml1plugindump.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qmlbundle.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qmlimportscanner.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qmllint.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qmlmin.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_qmlprofiler.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_uic.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri:
C:\Qt\5.4.2\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri:
C:\Qt\5.4.2\qtbase\mkspecs\features\qt_functions.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\qt_config.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\win32\qt_config.prf:
C:\Qt\5.4.2\qtbase\mkspecs\win32-g++\qmake.conf:
C:\Qt\5.4.2\qtbase\mkspecs\features\spec_post.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\default_pre.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\win32\default_pre.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\resolve_config.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\default_post.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\win32\rtti.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\precompile_header.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\warn_on.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\qt.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\resources.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\moc.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\uic.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\win32\windows.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\testcase_targets.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\exceptions.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\yacc.prf:
C:\Qt\5.4.2\qtbase\mkspecs\features\lex.prf:
ChipCoin.pro:
C:/QT/5.4.2/qtbase/lib/qtmain.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Core.prl:
C:/QT/5.4.2/qtbase/lib/Qt5WebKitWidgets.prl:
C:/QT/5.4.2/qtbase/lib/Qt5WebKit.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Gui.prl:
C:/QT/5.4.2/qtbase/lib/qtharfbuzzng.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Network.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Sensors.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Positioning.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Multimedia.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Sql.prl:
C:/QT/5.4.2/qtbase/lib/Qt5Widgets.prl:
C:/QT/5.4.2/qtbase/lib/Qt5MultimediaWidgets.prl:
C:/QT/5.4.2/qtbase/lib/Qt5PrintSupport.prl:
C:/Qt/5.4.2/qtbase/plugins/platforms/qwindows.prl:
C:/QT/5.4.2/qtbase/lib/Qt5PlatformSupport.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qdds.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qicns.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qico.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qjp2.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qmng.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qtga.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qtiff.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qwbmp.prl:
C:/Qt/5.4.2/qtbase/plugins/imageformats/qwebp.prl:
C:/Qt/5.4.2/qtbase/plugins/bearer/qgenericbearer.prl:
C:/Qt/5.4.2/qtbase/plugins/bearer/qnativewifibearer.prl:
qmake: FORCE
	@$(QMAKE) USE_UPNP=- -o Makefile ChipCoin.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
	-$(DEL_FILE) D:\ChipCoin\src\leveldb\libleveldb.a;
	-$(DEL_FILE) cd
	-$(DEL_FILE) D:\ChipCoin\src\leveldb
	-$(DEL_FILE) ;
	-$(DEL_FILE) clean
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) D:\ChipCoin\chipcoin_plugin_import.cpp

D:/ChipCoin/src/leveldb/libleveldb.a: FORCE

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
